# Библиотеки Python для Data Science: Numpy, Matplotlib, Scikit-learn

## Урок 2. Вычисления с помощью Numpy. Работа с данными в Pandas

### Вычисления с помощью Numpy

In [1]:
import numpy as np
import pandas as pd

#### Задание 1

Создайте массив Numpy под названием `a` размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа `1, 2, 3, 3, 1`, а второй - числа `6, 8, 11, 10, 7`. Будем считать, что каждый столбец – это признак, а строка – наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив `mean_a`, в нем должно быть 2 элемента.

In [2]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a.shape

(5, 2)

In [3]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

#### Задание 2

Вычислите массив `a_centered`, отняв от значений массива `а` средние значения соответствующих признаков, содержащиеся в массиве `mean_a`. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3

Найдите скалярное произведение столбцов массива `a_centered`. В результате должна получиться величина `a_centered_sp`. Затем поделите `a_centered_sp` на `N-1`, где `N` - число наблюдений.

In [5]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp

np.float64(8.0)

In [6]:
N = a.shape[0]
a_centered_sp / (N - 1)

np.float64(2.0)

#### Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве `а`. \
В задании 4 мы делили сумму произведений центрированных признаков на `N-1`, а не на `N`, поэтому полученная нами величина является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции `np.cov`. \
В качестве аргумента `m` функция `np.cov` должна принимать транспонированный массив `a`. \
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [7]:
cov_mrx = np.cov(a.T)
cov_mrx

array([[1. , 2. ],
       [2. , 4.3]])

In [8]:
cov_mrx[0][1]

np.float64(2.0)

### Работа с данными в Pandas

#### Задание 1

Создайте датафрейм `authors` со столбцами `author_id` и `author_name`, в которых соответственно содержатся данные: \
[1, 2, 3] \
['Тургенев', 'Чехов', 'Островский']

Затем создайте датафрейм `books` cо столбцами `author_id`, `book_title` и `price`, в которых соответственно содержатся данные: \
[1, 1, 1, 2, 2, 3, 3] \
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'] \
[500, 400, 300, 350, 450, 600, 200]

In [9]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 
                        'author_name': ["Тургенев", "Чехов", "Островский"]})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [10]:
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 
                      'book_title': ["Отцы и дети", "Рудин", "Дворянское гнездо", "Толстый и тонкий", "Дама с собачкой", "Гроза", "Таланты и поклонники"], 
                      'price': [500, 400, 300, 350, 450, 600, 200]})
books

author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200

#### Задание 2

Получите датафрейм `authors_price`, соединив дата фреймы `authors` и `books` по полю `author_id`.

In [11]:
authors_price = authors.merge(books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200

#### Задание 3

Создайте датафрейм `top5`, в котором содержатся строки из `authors_price` с пятью самыми дорогими книгами.

In [12]:
top5 = authors_price.nlargest(5, "price")
top5

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

#### Задание 4

Создайте датафрейм `authors_stat` на основе информации из `authors_price`. \
В датафрейме `authors_stat` должны быть четыре столбца: `author_name`, `min_price`, `max_price` и `mean_price`, \
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [13]:
authors_stat = authors_price.groupby("author_name")\
                            .agg(min_price=("price", "min"), max_price=("price", "max"), mean_price=("price", "mean"))\
                            .reset_index(drop=True)
authors_stat

min_price  max_price  mean_price
0        200        600       400.0
1        300        500       400.0
2        350        450       400.0

#### Задание 5**

Создайте новый столбец в датафрейме `authors_price` под названием `cover`, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка: \
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

Просмотрите документацию по функции `pd.pivot_table` с помощью вопросительного знака.

Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. \
Используйте для этого функцию `pd.pivot_table`. \
При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. \
Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy. \

Назовите полученный датасет `book_info` и сохраните его в формат `pickle` под названием "book_info.pkl". \
Затем загрузите из этого файла датафрейм и назовите его `book_info2`. \
Удостоверьтесь, что датафреймы `book_info` и `book_info2` идентичны.

In [14]:
authors_price["book_cover"] = ["твердая", "мягкая", "мягкая", "твердая", "твердая", "мягкая", "мягкая"]

In [15]:
pd.pivot_table?

In [16]:
book_info = pd.pivot_table(authors_price, 
                           values="price", 
                           index="author_name", 
                           columns="book_cover", 
                           aggfunc="sum", 
                           fill_value=0)
book_info

book_cover   мягкая  твердая
author_name                 
Островский      800        0
Тургенев        700      500
Чехов             0      800

In [17]:
book_info.to_pickle("book_info.pkl")

In [18]:
book_info2 = pd.read_pickle("book_info.pkl")
book_info2

book_cover   мягкая  твердая
author_name                 
Островский      800        0
Тургенев        700      500
Чехов             0      800

In [19]:
book_info.equals(book_info2)

True